// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSzJAFKNxsQdVsrkkFbygl5eLApFzDLo',
    appId: '1:388389040333:web:8aa53c9fb210e654bef984',
    messagingSenderId: '388389040333',
    projectId: 'sona-dfee3',
    authDomain: 'sona-dfee3.firebaseapp.com',
    storageBucket: 'sona-dfee3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFVybCNW-4CmdXfo4CagEh-Ec8vP3i8g',
    appId: '1:388389040333:android:58a8704a7d2c176fbef984',
    messagingSenderId: '388389040333',
    projectId: 'sona-dfee3',
    storageBucket: 'sona-dfee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijjOu2NVlaDm0NB-2fpCeHZaO4rTAPyE',
    appId: '1:388389040333:ios:df810e6879de7da4bef984',
    messagingSenderId: '388389040333',
    projectId: 'sona-dfee3',
    storageBucket: 'sona-dfee3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCijjOu2NVlaDm0NB-2fpCeHZaO4rTAPyE',
    appId: '1:388389040333:ios:df810e6879de7da4bef984',
    messagingSenderId: '388389040333',
    projectId: 'sona-dfee3',
    storageBucket: 'sona-dfee3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgSzJAFKNxsQdVsrkkFbygl5eLApFzDLo',
    appId: '1:388389040333:web:c61077813fa83399bef984',
    messagingSenderId: '388389040333',
    projectId: 'sona-dfee3',
    authDomain: 'sona-dfee3.firebaseapp.com',
    storageBucket: 'sona-dfee3.firebasestorage.app',
  );
}
